### ISSUE TITLE
Publish a version which is not depending on ihe.formatcode current

### ISSUE THREAD

**Issue by oliveregger** [IHE/QEDm#8]
We would like to use this IG for validation at the IHE CAT.
Is it possible to publish a version and to not have dependencies to current IG's?

**Comment by JohnMoehrke** [comment]
QEDm? This is not yet a released publication.  There have been no review of the content. The project is not a formal project.  See https://github.com/IHE/QEDm#conversion-plan 

Is there interest in the current publication form? Or are you interested in the future when it is harmonized with IPA? Please explain what it is you expect.

**Comment by oliveregger** [comment]
we have the https://gazelle.ihe.net/GMM/testing/testsDefinition/viewTestPage.seam?id=13575&testKeyword=QEDm_Provenance_Resource_Check test where we wan't to verify that the provenance is right, this is for the current pdf specification.

**Comment by JohnMoehrke** [comment]
The Provenance profile is now in the mXDE profile. The use-case for Provenance is mXDE, thus this is where it is properly and now published
https://profiles.ihe.net/ITI/mXDE/index.html

**Comment by oliveregger** [comment]
no, they differ, qedm has currently other requirements:

• Provenance.policy shall contain the static URI “urn:ihe:pcc:qedm:2017:documentprovenance-policy”.

**Comment by JohnMoehrke** [comment]
You can put in a comment against mXDE. 

mXDE went through public-comment and that did not come forward. In the public-comment the movement of Provenance to mXDE was a specific highlight. There was no concern brought up at that time. Therefore that is the new canonical and profile for the concept.

**Comment by oliveregger** [comment]
the resource check is referring to the qedm definition, as long as this is not updated, I don't understand why we should use mXDE.
